import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const iranSans = localFont({
  src: [
   
    {
      path: "../../public/fonts/IRANSansWeb.eot",
      style: "light",
    },
    {
      path: "../../public/fonts/IRANSansWeb.ttf",
      style: "medium",
    },
    {
      path: "../../public/fonts/IRANSansWeb.woff",
      style: "regular",
    },
  ],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa">
      <body
       dir="rtl" style={{direction:'rtl'}}
        className={cn(
          "bg-gray-100 font-sans",
          iranSans.variable
        )}>
        <div className="h-screen min-h-dvh flex justify-center">
          <div className="w-full h-full relative max-w-100  min-h-dvh bg-white flex flex-col ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
